apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: jitsi-jibri
  name: jitsi-jibri-auth
  namespace: jitsi
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      k8s-app: jitsi-jibri
  template:
    metadata:
      labels:
        k8s-app: jitsi-jibri
    spec:
      hostAliases:
        - ip: '127.0.0.1'
          hostnames:
            - example.com
      containers:
        - name: web
          image: jitsi/web:stable-4857
          resources:
            limits:
              cpu: "100m"
              memory: 1024Mi
            requests:
              cpu: "50m"
              memory: 50Mi
          envFrom:
            - configMapRef:
                name: jitsi-env
        - name: jicofo
          image: jitsi/jicofo:stable-4857
          resources:
            limits:
              cpu: "200m"
              memory: 1024Mi
            requests:
              cpu: "100m"
              memory: 256Mi
          envFrom:
            - configMapRef:
                name: jitsi-env
        - name: prosody
          image: jitsi/prosody:stable-4857
          resources:
            limits:
              cpu: "100m"
              memory: 1024Mi
            requests:
              cpu: "50m"
              memory: 128Mi
          envFrom:
            - configMapRef:
                name: jitsi-env    
        - name: jvb
          image: jitsi/jvb:stable-4857
          resources:
            limits:
              cpu: "4000m"
              memory: 8192Mi
            requests:
              cpu: "500m"
              memory: 512Mi
          envFrom:
            - configMapRef:
                name: jitsi-env 
        - name: jibri
          image: jitsi/jibri:stable-4857
          resources:
            limits:
              cpu: "3000m"
              memory: 8192Mi
            requests:
              cpu: "500m"
              memory: 2048Mi
          envFrom:
            - configMapRef:
                name: jitsi-env
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_BIND_SERVICE
                - SYS_ADMIN
          volumeMounts:
            - mountPath: /dev/snd
              name: dev-snd
            - mountPath: /dev/shm
              name: dev-shm
            - mountPath: /config
              name: config
          securityContext:
            privileged: true
      volumes:
        - name: dev-snd
          hostPath:
            path: /dev/snd
        - name: dev-shm
          hostPath:
            path: /dev/shm
        - name: config
          hostPath:
            path: /your/mount/path # Change your mount
      
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: jitsi-env
  namespace: jitsi
data:
  #ENABLE_AUTH: "1"
  #ENABLE_GUESTS: "1"
  AUTH_TYPE: internal
  DOCKER_HOST_ADDRESS: example.com
  PUBLIC_URL: https://example.com
  XMPP_BOSH_URL_BASE: http://127.0.0.1:5280
  XMPP_AUTH_DOMAIN: auth.example.com
  XMPP_MUC_DOMAIN: muc.example.com
  XMPP_GUEST_DOMAIN: guest.example.com
  XMPP_INTERNAL_MUC_DOMAIN: internal.muc.example.com
  XMPP_RECORDER_DOMAIN: recorder.example.com
  XMPP_SERVER: example.com
  XMPP_DOMAIN: example.com
  JICOFO_AUTH_USER: focus
  JICOFO_AUTH_PASSWORD: jicofoauthpassword
  JICOFO_COMPONENT_SECRET: jicofocomponentsecret
  JVB_AUTH_USER: jvb
  JVB_AUTH_PASSWORD: jvbauthpassword
  JVB_BREWERY_MUC: jvbbrewery
  JVB_PORT: "30100"
  JVB_TCP_PORT: "4443"
  JVB_STUN_SERVERS: meet-jit-si-turnrelay.jitsi.net:443
  JVB_TCP_HARVESTER_DISABLED: "true"
  JIBRI_XMPP_USER: jibri
  JIBRI_XMPP_PASSWORD: jibriauthpass
  JIBRI_BREWERY_MUC: JibriBrewery
  JIBRI_RECORDER_USER: recorder
  JIBRI_RECORDER_PASSWORD: jibrirecorderpass
  JIBRI_RECORDING_DIR: /config/recordings
  JIBRI_FINALIZE_RECORDING_SCRIPT_PATH: /config/finalize.sh
  JIBRI_STRIP_DOMAIN_JID: muc
  JIBRI_LOGS_DIR: /config/logs
  JIBRI_PENDING_TIMEOUT: "90"
  ENABLE_RECORDING: "1"
  DISPLAY: :0
  TZ: Europe/Berlin
  DISABLE_CERTIFICATE_VERIFICATION: "true"
  ENABLE_HTTP_REDIRECT: "1"
  #ENABLE_LETSENCRYPT: "1"
  #LETSENCRYPT_DOMAIN: ""
  #LETSENCRYPT_EMAIL: ""

---

apiVersion: v1
kind: Service
metadata:
  labels:
    service: jvb-jitsi
  name: jitsi-jvb-udp
  namespace: jitsi
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - port: 30100
    protocol: UDP
    targetPort: 30100
    nodePort: 30100
  selector:
    k8s-app: jitsi-jibri

---

apiVersion: v1
kind: Service
metadata:
  labels:
    service: jitsi-web
  name: jitsi-web
  namespace: jitsi
spec:
  #externalIPs:  #if have a external ip
  #- xxx.xxx.xxx.xxx 
  #externalTrafficPolicy: Cluster
  ports:
  - name: "http"
    port: 80
    targetPort: 80
    nodePort: 30102
  - name: "https"
    port: 443
    targetPort: 443
    nodePort: 30101
  type: NodePort
  selector:
    k8s-app: jitsi-jibri